#!/home/ocean/anaconda3/bin/python3
from numpy import cos, arccos, sin, arctan, tan, pi, sqrt; from numpy import array as ary; import numpy as np; tau = 2*pi
from matplotlib import pyplot as plt

#Stores the functions for reading from .out files generated by MCNP-4C2.
def ReadBlockOfText(fname,trigger1,length,trigger2="",ScrollMore=1):
	assert type(trigger1)==str
	assert type(trigger2)==str
	assert type(length)==int
	f=open(fname,"r")
	FastScroll, SlowScroll=True,True
	if trigger2=="":
		SlowScroll=False
	data=[]
	f.seek(0)
	while FastScroll:
		if trigger1 in f.readline():
			FastScroll=False
			#stop scrolling
	while SlowScroll:
		#keep scrolling until it reaches the column headers line
		if trigger2 in f.readline():
			SlowScroll=False
	[f.readline() for s in range(ScrollMore)] #scroll (skip) 1 more line to get to the data
	for particle in range(length):
		line=[s for s in f.readline().split() if s]#split line
		data.append(line)
	f.close()
	return data
def IsEven(Number):
	assert type(Number)==int
	if Number%2==0:
		return True
	else:
		return False
def ConvToDict(array,namelist):
	assert len(array)==len(namelist)
	new_ar={}
	for i in range(len(array)):
		assert type(namelist[i])==str, "Please provide a string as the dictionary key"
		new_ar[namelist[i]]=array[i]
	return new_ar